version: '3.8'

services:
  whatsapp: 
    image: devlikeapro/whatsapp-http-api
    ports:
      - "5001:3000"
    container_name: whatsapp
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./db:/data/db


  
